[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
itertools = "0.12.1"
proconio = "0.4.5"
svg = "0.9.0"
wasm-bindgen = "0.2.92"
